### ISSUE TITLE
Naming Pipes' controllers

### ISSUE THREAD

**Issue by deeleman** [mgechev/angular2-style-guide#11]
Perhaps a bit too anal after the discussion held at #4 but in order to leave no room for doubt, may be it would be worth to specify a convention for Pipes controller classes as well.

Currently the [framework itself](https://github.com/angular/angular/blob/master/modules/angular2/src/common/pipes.ts) defines the builtin pipes modules with a combination of name plus the `Pipe` suffix. It seems logical to follow the same convention and state it somewhere in the guide if everybody's fine with it.

**Comment by mgechev** [comment]
I agree. Would you open a PR?

**Comment by deeleman** [comment]
sure! will do it along the weekend ;)

**Comment by deeleman** [comment]
Actually I'd like to push the discussion a bit further. In the same way that we have discussed best practices for naming directive selectors, I believe we should discuss/define a common ground on this as well.

Right now all builtin pipes are usually represented in lowercase only. We do see the following:

``` html
<p>{{ fullName | lowercase }}</p>
```

Instead of this (please note the camel cased `lowerCase`):

``` html
<p>{{ fullName | lowerCase }}</p>
```

But as far as I'm aware there is not a single public recommendation for best practices on this. While common sense should reign on this matter, and at the risk of being too anal, do you guys think is it worth settling a recommendation for **naming pipes in lowercase** only?

Let me know your thoughts.

**Comment by mgechev** [comment]
I prefer the camelCase naming, seems more readable especially on pipes with longer name.

**Comment by deeleman** [comment]
I prefer camelCasing too, and readability is always a strong argument. :)

I guess there will be a common agreement on this one, but let's leave this issue open a couple of days in case anyone wants to participate. A PR will follow up with the guidelines for naming Pipes' controller classes.

**Comment by deeleman** [comment]
Apparently I was wrong when stated that the naming tokens found in the framework were all lowercased and there it is `orderBy` or `limitTo` (currently in the project backlog) to prove me wrong. At the light of this I've attached a note (and a example summary) in the PR.

**Comment by mgechev** [comment]
Fixed by https://github.com/mgechev/angular2-style-guide/pull/12
