### ISSUE TITLE
Supporting ESLint as an "or" option to JSCS / JSHint

### ISSUE THREAD

**Issue by joshwiens** [mgechev/angular2-style-guide#13]
I've recently converted over to ESLint from the standard jscs / jshint mainly for the pluggable nature of it.

Would you consider a PR for a standard ESLint configuration?

Also, I was going to create .rc files for for jscs, jshint, tslint to go along with snippets once the style has settles enough to do so.
- [x] Add ESLint configuration
- [x] Move linting configurations into .rc files
- [ ] Move rules explanation into Linting.MD and link to README.md

**Comment by mgechev** [comment]
Yes, including ESLint configuration seems like a good idea. Looking forward for your PR!
