### ISSUE TITLE
Drop models

### ISSUE THREAD

**Issue by mgechev** [mgechev/angular2-style-guide#24]
## Introduction

Currently we have the following entity types:
- `components`
- `directives`
- `pipes`
- `services`
- `models`
## Problem

This does not completely align to the concepts defined by Angular 2, since the framework doesn't include `models`.

Although it is typical scenario to have entities which represent the domain, in some architectures such as flux and redux having models is optional. In these architectures we have Stores, Actions, Dispatchers, Components, Reducers, etc. but we do not have recommendations on how we should present the business model and/or communicate with services.

The style guide aims to be agnostic in terms of language (we have separate sections for this) and micro-architecture.
## Proposal

My suggestion is to drop the `models` entity from the style guide since this way we are implicitly implying usage of MV\* approach.

// cc @evanplaice @nareshbhatia @d3viant0ne @ludohenin

**Comment by ludohenin** [comment]
> Although it is typical scenario to have entities which represent the domain

Considering your statement, maybe highlighting this is optional is better than just dropping models

**Comment by evanplaice** [comment]
@mgechev I'm cool with dropping the models. I used them in my reusable components but I haven't come across any other examples that use them.

Most example projects found online assume that the data received from a HTTP request will be used as-is. Models are definitely optional.

**Comment by mgechev** [comment]
Last days I was thinking about this further.

I think we should not introduce a new concept (such as models) but dropping this suffix will have impact on the semantics of the directory structure. Having only `components`, `directives`, `services` and `pipes` doesn't seem enough in most situations.

What I was thinking about is just to include additional section in the style guide (may be subsection of the "Directory Structure") where we explicitly provide guidelines for naming files such as `stores`, `models`, `reducers`, `actions` etc. depending on the chosen architecture.

It will be something like:

> - Name the files which contain component, directives, pipes and services definition with the corresponding suffix.
> - Apply the same naming convention to application-specific modules. For instance in case of flux/redux based architecture use suffixes specific for the code units' types.
> 
> **EXAMPLE**
> 
> ```
> // Contains the "home-dashboard" component
> home-dashboard.component.ts
> 
> // Contains the ShoppingCart model.
> shopping-cart.model.ts
> 
> // Contains the ShoppingCart model.
> todo.reducer.ts
> 
> // Contains the logic for the "checkout" service.
> checkout.service.ts
> ```

Let me know what you think.

**Comment by ludohenin** [comment]
Looks good to me.
Shouldn't this `shopping-cart.model.ts` be `shopping_cart.model.ts` ?

**Comment by mgechev** [comment]
My initial idea was to use `_` as well but this way we won't be following the Angular's dev guide on angular.io and we won't be backwards compatible with [AngularJS 1.x style guides](https://github.com/mgechev/angular2-style-guide/issues/7#issuecomment-180007840).

**Comment by evanplaice** [comment]
@mgechev :+1:

Good point about reducers with the release of ngrx store. There's a lot of progress being made in terms of async workflows. Who knows what else will be added in the near/distant future.

Making the suffix a standard practice seems like a sound practice.

**Comment by joshwiens** [comment]
@mgechev - Separating more **advanced topics** from the base directory structure section is probably the best way to go. IMO things like model / stores / reducers become more common for large scale applications or in my case, where I am consuming data from a legacy API where a model is preferable to screwing around with existing sprocs.

They have their place, but may only prove to confuse a .jr developer or dilute the core concepts of the guide.

 "If you want to read about X, go here"  :+1: 

And I also like the "suffix as a standard" approach. Makes life much easier for code reviews / looking through unfamiliar code. There is no guessing what something does, it's evident just looking at the file tree.

**Comment by evanplaice** [comment]
@d3viant0ne I wonder if it would be worthwhile to add a directory with advanced guides.

I've been thinking about the best way to distill down the API suggestions into a few simple rules but I think it would be beneficial to keep the existing guide as a separate document for developers looking for a more in-depth description of their usage. I have a few more sections covering grouping exports and how tree shaking is used to reduce bundle sizes.

The same could be said for directory structures. Provide a few simple rules in the style guide and provide a more in-depth guide that covers the different levels of complexity for larger/advanced projects.

**Comment by joshwiens** [comment]
@evanplaice - Given the eventuality of going to gitbook I think it will be easier to break up the content in a way that is easier to consume.

That said, I think we should be careful about delivering core concepts in a clear & concise way while providing an easy to find section of related advanced architecture / topics.
