### ISSUE TITLE
Name events without prefix 'on'

### ISSUE THREAD

**Issue by sbley** [mgechev/angular2-style-guide#27]
I would suggest the following naming convention for events:

Name events without the prefix 'on'. Name your event handler methods with the prefix 'on' followed by the event name.

``` ts
/* WRONG */
<my-voter (onVoted)="onVoted($event)"></my-voter>
```

``` ts
/* CORRECT */
<my-voter (voted)="onVoted($event)"></my-voter>
```

_Why?_: This is to be consistent with built-in events like button clicks:

``` ts
<button (click)="showDetails()">Show Details</button>
```

_Why?_: Angular allows for an alternative syntax `on-*`. If the event itself was prefixed with 'on' this would result in an `on-onEvent` binding expression.

``` ts
/* CORRECT */
<my-voter (voted)="onVoted($event)"></my-voter>
<my-voter on-voted="onVoted($event)"></my-voter>
```

**Comment by mgechev** [comment]
This sounds good to me. Do you want to open a PR?
