### ISSUE TITLE
awesome....

### ISSUE THREAD

**Issue by born2net** [mgechev/angular2-style-guide#3]
love the article... looking forward for more advanced topics. please expand on detachment of elements

**Comment by e-oz** [comment]
thanks for spreading best practices :)
I disagree with just 3 moments in this big list, so I'll be glad to promote it too.

**Comment by mgechev** [comment]
@e-oz let us know what you don't agree with. We can discuss it and update the guidelines when we reach an intersection.

**Comment by mgechev** [comment]
@e-oz nevermind, just saw your suggestions. I think I agree on most of them, I'll comment later/tomorrow.

**Comment by mgechev** [comment]
@born2net done.
