### ISSUE TITLE
Variable, property namings

### ISSUE THREAD

**Issue by buehler** [mgechev/angular2-style-guide#32]
Hey @mgechev 

Awesome job!

I'd consider a word or two about the general variable namings. Since TypeScript is strongly influenced by C# and uses many of it's principles, I'd suggest the following things:
- public variables are named `camelCase` without a leading `_`

Why? They are accessible like functions or properties, so they should inherit the same naming structure.
- private variables should be named `_camelCase` with a leading `_`

Why? Because they are private and should not be accessible from outside the class. In addition to that, when properties are used, the variable cannot have the same name as the property.

``` typescript
class MyClass {
    private _onlyForMyClass:number = 42;
    private _leet:number = 1337;
    public foo:string = 'bar';

    public get leet():number {
        return this._leet;
    }

    //and a possible setter
    public set leet(value:number){
        this._leet = value;
    }
}
```

What are your thoughts?

Cheers
Chris

**Comment by mgechev** [comment]
@buehler thanks! It makes sense to add such rule in the TypeScript section. I agree with you that it makes sense.

tslint's `variable-name` rule seems to solve this partially so we can extend the `tslint.json` configuration as well.

We can extend the rule further in ng2lint where we can check whether variable with leading `_` is declared with private access modified.

**Comment by buehler** [comment]
Yay ;-)

**Comment by buehler** [comment]
Perfect, I'll wait for the new package then ;-)
Thanks for the cool styleguide!

Or should I make a PR?
Cheers

**Comment by mgechev** [comment]
You're welcome to open a PR with this addition to the TypeScript section :-)

**Comment by buehler** [comment]
I found a styleguide by Microsoft:
https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Classes.md

Well, they say, "name private vars without _ unless it's for a property"

I'll write an appropriate part for the typescript section

**Comment by ludohenin** [comment]
@mgechev private members lint rule is already available from the angular2 repo.
https://github.com/angular/angular/blob/master/tools/tslint/requireInternalWithUnderscoreRule.ts

**Comment by buehler** [comment]
Alright, I documented it in #33 
Feel free to comment on the PR if you find something that is missing or needs improvement.

Cheers
