### ISSUE TITLE
Where to put application interfaces?

### ISSUE THREAD

**Issue by pauleveritt** [mgechev/angular2-style-guide#34]
In Tour of Heroes, class HeroDetailComponent has a hero property which implement the Hero interface :

https://github.com/angular/angular.io/blob/7e86e9411bfbd4effbcc269f8965939d2cb29a69/public/docs/_examples/tutorial/ts/app/hero-detail.component.ts#L11

The tour puts the Hero interface in ./hero.ts. Some questions:
- Every other filename in the tutorial encodes what kind of thing it is, e.g. app.component.ts. IMO, this filename should have been hero.interface.ts or as your guide says, "corresponding suffix".
- In _theory_, interfaces are distinct from implementation. Many tutorials so far, though, just use interfaces in type declarations, not in class statements. Still, should the file with the interface be in the "bounded context"?
- Based on your "single reason to change" (single responsibility principle), should each interface be in a separate file, with only the interface in the file? Should it be a default export or a named export?

**Comment by evanplaice** [comment]
> Every other filename in the tutorial encodes what kind of thing it is, e.g. app.component.ts. IMO, this filename should have been hero.interface.ts or as your guide says, "corresponding suffix".

Yes. The reason being, if a facade is added as a public API for the bounded context it would be named hero.ts. An issue can be filed with the Angular.io repo but the project is managed by Google so there's no guarantee that they will conform to this (ie the community driven) style guide.

> In theory, interfaces are distinct from implementation. Many tutorials so far, though, just use interfaces in type declarations, not in class statements. Still, should the file with the interface be in the "bounded context"?

It _can_ be included in the bounded context if it applies only to that bounded context. In the bigger picture of things, logically grouping files that apply to a specific bounded context makes it much easier to reuse the code elsewhere. 

There's nothing stopping you from grouping interfaces at the application-level under `/shared/interfaces` if that makes more sense for your application structure.

> Based on your "single reason to change" (single responsibility principle), should each interface be in a separate file, with only the interface in the file? Should it be a default export or a named export?

Good question. In Angular2, component definitions use named exports, pipes use named exports, services use named exports, etc. I assume it would make sense to avoid breaking convention and use named exports for interfaces as well.

When is it a good idea to use default exports? I can think of 2 good cases. First, libraries/modules that need to provide legacy-style script imports. Second, libraries/modules that provide an 'everything and the kitchen sink' import.

For example, with rxjs you can use `import 'rxjs';` to import the entire lib including 95% of the operators/features that you'll never use in production. It's good for getting started and experimenting with new features. Not so good when it comes time to optimize for size/performance.

**Comment by pauleveritt** [comment]
Thanks @evanplaice for the reasoning, which all makes sense. So to wrap up, should the style guide discuss interfaces?

**Comment by joshwiens** [comment]
@pauleveritt There is discussion ( #24 ) about having an "Advanced Topics" section which imo where this should be spec'd. We should definitely provide guidance but like models & reducers it should be done in a way that doesn't add excess complexity when trying to mentally consume the core style guide.

**Comment by pauleveritt** [comment]
Makes sense.
