### ISSUE TITLE
Suggest naming facade files 'index.ts' rather than 'feature.ts'

### ISSUE THREAD

**Issue by jimitndiaye** [mgechev/angular2-style-guide#37]
This allows the exports from a feature to  be accessed by `import {FeatureExport} from 'app/feature';` rather than `import {FeatureExport} from 'app/feature/feature';`

The Angular 2 source uses the similar patterns. As an alternative you could have the façade file for a feature as feature.ts located at the root of the app folder, as a sibling of the feature folder. This results in the same import syntax except that you have feature code bleeding out into the app folder. I personally prefer the index.ts option.

**Comment by evanplaice** [comment]
> This allows the exports from a feature to be accessed by import {FeatureExport} from 'app/feature'; rather than import {FeatureExport} from 'app/feature/feature';

AFAIK, index.ts doesn't work the same on the client-side as it does in Node.js. Although, that would be an ideal solution.

---

For example, the following doesn't work. At least for Angular2 + ES6 + Traceur. Maybe it does for Angular2 + Typescript.

``` bash
|- app
   |- feature
      |- index.ts
      |- feature.ts
   |- consumer
      |- consumer.ts  
```

_index.ts_

``` javascript
export { FeatureExport } from './feature.ts';
```

_consumer.ts_

``` javascript
import { FeatureExport } from 'app/feature';
```

---

> The Angular 2 source uses the similar patterns. As an alternative you could have the façade file for a feature as feature.ts located at the root of the app folder, as a sibling of the feature folder. This results in the same import syntax except that you have feature code bleeding out into the app folder. I personally prefer the index.ts option.

This was already addressed in #34 

The short version is, with this strategy the facade isn't contained within the bounded context. So, the context can't be extracted for re-use without affecting the structure.

Consider you create a feature in one project and decide to host it as a separate project to reuse across many applications. Generally, the directory structure for a reusable library will only contain one context with the facade contained within the root directory.

So if the `feature` context is extracted for reuse...

``` bash
|- app
   |- feature.ts  //  <-  facade outside context
   |- feature
      |- feature.ts
   |- consumer
      |- consumer.ts
```

...it'll become.

``` bash

|- /
   //  <-  facade will have to be re-created
   |- feature.ts
```

If you keep the facade in the parent directory, you'll be forced to recreate it when the code is extracted into its own repo.

---

I _do_ agree that naming the facades `index.js` is probably a better practice. Hopefully, when the ES6 spec and implementations solidify, folders containing `index.js` function the same way as they do in Node.js.

``` javascript
import { FeatureExport } from 'app/feature'; //  <-  This would be awesome
```
