### ISSUE TITLE
Naming components' and directives' controllers

### ISSUE THREAD

**Issue by mgechev** [mgechev/angular2-style-guide#4]
## Introduction

Currently the style guide states that they should be suffixed with `Ctrl`. Although this is correct it doesn't brings a lot of semantics.
## Suggestion

My suggestion is to change it to the following:
- `CustomPrefix` + `BasicDescription` + `Dir` or `Cmp`

For instance:

``` ts
// ui.js

@Directive({
  selector: '[sc-tooltip]'
})
export class ScTooltipDir { ... }
```
## Pros

By following this convention for the end user of the directive will be clear that:
- The the imported code unit is a directive (by the `Dir` suffix).
- The selector of the directive is `sc-tooltip`.
- The type of the selector of the directive is an attribute.
## Cons

I don't see any serious cons in the lack of `Ctrl` as suffix.

// cc @gdi2290 @ludohenin @NathanWalker @PascalPrecht

**Comment by PatrickJS** [comment]
for me it's either `.component / Component` or `.cmp / Cmp` but then you also have directives `.directive / Directive`

**Comment by mgechev** [comment]
@gdi2290 basically you agree with the suggestion? I prefer `Cmp`/`Dir` over `Component`/`Directive` because the latter is more verbose.

**Comment by PatrickJS** [comment]
It's a question of how far you go with naming. Same with services etc. If the name of the class is different then the selector is that alright? Do you include namespaces for the selectors or prepend during build steps? What do you gain and what do you lose since everything is a tradeoff. (amazing logo btw)

**Comment by lennonjesus** [comment]
Sometimes I like more verbose names. So, `Component / Directive` it's ok for me.

**Comment by antonybudianto** [comment]
I also preferred `Component / Directive` one

**Comment by cyrilletuzi** [comment]
The Tour of Heroes, main part of the little documentation available for now, already suggests to use a "AppComponent" name style for components for quite some time. As Angular 2 is now used in real applications, I think it's better to not change to "Cmp" and have to rewrite everything just for a few letters. And personally I prefer a verbose convention.

I don't think it's a good idea to bring "Ctrl" in this story. Even if the idea is still there under the hood, the Controller concept is not one the 8 main Angular 2 building blocks. People starting with Angular 2, not knowing Angular 1, will be confused.

**Comment by NathanWalker** [comment]
My litmus test comes when stacking any standard against a large application with many hundreds of files. 

While being verbose makes sense and is quite nice in a relatively small application, IMHO, the flipside is that being verbose in a large application becomes quite burdensome. I compare it to reading a legal handbook with hundreds of footnotes and political correctness. It not only burdens the mind, but also causes eye fatigue.

When dealing with hundreds of files, again IMHO, being short and succinct provides speed and ease of development. Just less to process on the screen. Not to mention that when on the go, working on a small laptop screen, opening a file nested 7-8 folders deep potentially and seeing it's full name side-by-side with other files (which may potentially have a similar name so seeing the full path and the name is important).

Option 1

```
/src/shared/frameworks/app.framework/core/directives/nw-tooltip.directive.ts
/src/shared/frameworks/web.framework/core/components/nw-tooltipmaker.component.ts
/src/shared/frameworks/mobile.framework/core/components/nw-tooltipmaker.component.ts
/src/shared/frameworks/desktop.framework/core/components/nw-tooltipmaker.component.ts
```

Option 2

```
/src/shared/frameworks/app.framework/core/directives/nw-tooltip.dir.ts
/src/shared/frameworks/web.framework/core/components/nw-tooltipmaker.cmp.ts
/src/shared/frameworks/mobile.framework/core/components/nw-tooltipmaker.cmp.ts
/src/shared/frameworks/desktop.framework/core/components/nw-tooltipmaker.cmp.ts
```

I don't know, to me Option 2 is bit more attractive.

**Comment by mgechev** [comment]
https://github.com/mgechev/angular2-style-guide/issues/5 is related. If we decide to approach the way that @ByJC suggests then I think more verbose name will be more reasonable.

If we bet on abbreviation instead of verbosity we need to come up with name for services (`srv`?!).

So if we stick to one "code unit" per file and strict naming convention for this file we can keep the components' and services' names simple and thus reduce typing.

For instance:

``` ts
// ./app/todo/todo_item/todo_item.component.ts

@Component({
  selector: 'sg-todo-item',
  template: `...`
})
export class SgTodoItem { ... }
```

We can require the component like:

``` ts
import {SgTodoItem} from './todo_item/todo_item.component';
...
```

This way when we reference the component's constructor we can use `SgTodoItem` and peek at the import in order to verify the type of the code unit. The only cons I see is collision with the names of the defined services (i.e. what if we have `TodoItem` service prefixed with `Sg`).

**Comment by deeleman** [comment]
> The only cons I see is collision with the names of the defined services (i.e. what if we have `TodoItem` service prefixed with `Sg`).

While I really like the `.component` (or `.whatever.ts`) filenaming approach in order to make class names less verbose, I do share this same concern. Obviously naming class names (and hence filenames) like `TodoItemService.service.ts` becomes fairly redundant.

**Comment by ByJC** [comment]
Maybe when you import the component and the service, in order to avoid collision, we can do something like that : (ie suffix the name with the type)

``` js
import {SgTodoItemComponent} from './todo_item/todo_item.component';
import {SgTodoItemService} from './todo_item/todo_item.service';
```

But I don't think the both of them will be import in the same file, more something like that :

todo_item.compoment.ts : 

``` js
import {SgTodoItemService} from './todo_item/todo_item.service';

@Component({
  selector: 'sg-todo-item',
  providers: [SgTodoItemService],
  template: `...`
})
export class SgTodoItem { ... }
```

@deeleman : I agree with you, the name of the file should be like : 
name.type.extension with type optional

ie : 

``` js
todo_item.component.ts
todo_details.service.ts
todo_details.html
 ...
```

**Comment by e-oz** [comment]
I disagree about custom prefixes - we have DI to solve name collisions, it's enough.

**Comment by evanplaice** [comment]
If the nested components, services, etc folder structure is used then suffixes aren't necessary.

Personally, I prefer verbose (ex `TodoComponent`, `TodoService`) for the module name, and no suffix on file names.

**Comment by Foxandxss** [comment]
I don't like any prefix to be honest and I wouldn't recommend them for my libraries.

**Comment by PatrickJS** [comment]
The di uses references so there aren't any naming collisions (because it's using `Map`). If we were using strings then we need the namespace.

**Comment by mgechev** [comment]
@gdi2290 true. By saying name collisions I mean collisions in the imports. They could be resolved pretty easily anyway:

``` ts
import {TodoItem as TodoItemComponent} from './todo-item.component';
import {TodoItem} from './todo-item';
```

In case there's no suffix, if you're scrolling a long file in order to verify the type of given unit you need to peek at its import at the beginning. Not a big problem but its worth mentioning :-).

**Comment by mgechev** [comment]
Based on our discussion the naming convention now is `BasicDescription` + `Component` or `Directive`.

This way we won't need to use the `as` operator in the component/directive import and we can keep the services without any suffix.
