### ISSUE TITLE
Using badge on personal Angular2 projects

### ISSUE THREAD

**Issue by francesco-strazzullo** [mgechev/angular2-style-guide#55]
Hi,
I have a Webpack+Angular2 stub that follows the styleguide. I want to use the badge on my github. It's possible?

**Comment by mgechev** [comment]
Sure, just copy & paste this snippet in the README.md of your project:

```
[![Angular 2 Style Guide](https://mgechev.github.io/angular2-style-guide/images/badge.svg)](https://angular.io/styleguide)
```
