### ISSUE TITLE
Module naming convention

### ISSUE THREAD

**Issue by dowrow** [mgechev/angular2-style-guide#7]
This guide says we should use this_case for module filenames opposed to the kebab-case convention (recommended by Papa John in his TourOfHeroes tutorial). I'm with Papa on this one, I find it more natural (also regular dashes are easier to type).

**Comment by deeleman** [comment]
I personally hate snake casing: I find it cumbersome, hard to type (hence error prone) and usually stands on the way when searching types by name, but that is actually the convention currently in use by the Angular 2 team for naming modules within the framework itself.

**Comment by mgechev** [comment]
Yes, that was my point. The Angular 2 core team uses [`lower_snake_case`](https://github.com/angular/angular/tree/master/modules/angular2/src/web_workers/ui) for naming modules.

**Comment by dowrow** [comment]
Looks like I'll have to be ok with it then, but it makes me slightly sad inside.

**Comment by mgechev** [comment]
Lets keep the issue open for a couple days and see what other folks think about the naming. The style guide aims to be community-driven so we're open for suggestions.

**Comment by e-oz** [comment]
I will not follow this rule too. Directives use dashes so it makes more sense to use them in names of folders.

**Comment by deeleman** [comment]
Nothing is set on stone obviously. It's up to everyone to embrace a coding convention or create one of his own, as long as it does the job and you and your team feel comfortable about it ;) 

With this said, dash-casing is now discouraged for naming directives: https://github.com/angular/angular/blob/master/modules/angular2/docs/migration/kebab-case.md#directives-and-components

**Comment by e-oz** [comment]
In previous comment I mostly meant components (habit from ng1). But about directives - we can follow either snake or dashes convention in names of folders/files, not kebab, because there are case insensitive file systems. So I prefer to use dashes here too, just to keep consistency.

**Comment by wardbell** [comment]
Strongly resist snake_casing. A1 style guide prefers dash-casing and we don't need more friction in transition. **Docs use dash-casing** and will continue to do so.

@deeleman   You misread that migration post. We gave up using dash/kebab case for names in binding position (within brackets and parens) in favor of **camelCase**.  Element names should be in dash-case, not snake_case.

> For tag names, the best practice is to keep them lower dash cased, do not update them,
> For attribute names, the best practice is to convert them from lower dash case to camel case.

**Comment by mgechev** [comment]
@wardbell has a solid argument for `dash-casing`. I'll update the style guide in the following terms:
- kebab-case naming for the modules.
- keep attribute names (including directives' selectors) camelCase.
- keep element names (including components' selectors) kebab-case.
