### ISSUE TITLE
Third-party libraries

### ISSUE THREAD

**Issue by mgechev** [mgechev/angular2-style-guide#8]
We need to make the style guide compatible with the angualar-cli based on [the last merge](https://github.com/angular/angular-cli/pull/173/files).

// cc @NathanWalker

**Comment by mgechev** [comment]
I guess including this example showing the default export:

``` ts

import {TestDirective} from './src/app/directives/test.directive';
import {TestService} from './src/app/providers/test.provider';
import {TestService2} from './src/app/providers/test2.provider';
import {TestPipe} from './src/app/pipes/test.pipe';
import {TestStyles} from './src/app/test.styles';

export * from './src/app/directives/test.directive';
export * from './src/app/providers/test.provider';
export * from './src/app/providers/test2.provider';
export * from './src/app/pipes/test.pipe';
export * from './src/app/test.styles';

export default {
  directives: [TestDirective],
  pipes: [TestPipe],
  providers: [TestService, TestService2],
  styles: TestStyles.styles(),
  styleUrls: ['src/app/css/test.css']
}
```

And adding [the bundler](https://github.com/angular/angular-cli/pull/173/files#diff-7cccb31e88ec922d344c82ae4c90ea8bR104) should be enough.

**Comment by NathanWalker** [comment]
@mgechev Linking the styleguide to the [Publisher Guide here would be good](https://github.com/angular/angular-cli/blob/master/docs/ng-install.md#b-publisher-guide-preparing-your-library).
